eureka:
  client:
    fetch-registry: false
server:
  port: 8222
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: NOTIFICATION-HANDLER
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/notification-handler/**
        - id: USER-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
        - id: NOTIFICATION-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/carts/**
        - id: SEARCH-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtAuthFilter
            - name: RateLimiter
              args:
                rateLimit: 50