eureka:
  client:
    fetch-registry: false
server:
  port: 8222
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PRODUCT-CATALOG
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: USER-MANAGEMENT
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
        - id: SHOPPING-CART
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/carts/**
        - id: ORDER-MANAGEMENT
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/orders/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/payments/**
        - id: NOTIFICATION-SERVICE
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/notifications/**